### ISSUE TITLE
[REQ] license file fix

### ISSUE THREAD

**Issue by MarcoRavich** [ConstantRobotics-Ltd/VStabiliser#3]
Hi there and happy new year: 1st of all thanks for your cool work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [VIDEO](https://github.com/forart/HyMPS#-1) \ [Processing page](https://github.com/forart/HyMPS/blob/main/Processing.md#--) \ [Stabilizers subsection](https://github.com/forart/HyMPS/blob/main/Processing.md#stabilizers-)), can you please add a "GH-compliant" license file ?

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/ConstantRobotics-Ltd/VStabiliser/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/ConstantRobotics-Ltd/VStabiliser/?label=LICENSE)

Anyway you can easily set a "compliant" one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve categorization/sorting of collected projects in order to push their evolution by favouring collaborations between developers (and not only).

Thanks in advance.

**Comment by ConstantRobotics** [comment]
Thank you! We will fix it soon. We're grateful for your advice.

**Comment by ConstantRobotics** [comment]
Version updated with GitHub compliant license.

**Comment by MarcoRavich** [comment]
Thanks, badge is correctly generated now.

note: check your 2.4.2 release date...
